name: 'built_test'
version: 0.0.1
description: A web server built using the shelf package.
#author: joel <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  shelf: '>=0.6.0 <0.7.0'
  built_collection: '^1.0.0'
  built_json: '^0.1.5'
  built_value: '^0.1.3'
  enum_class: '^1.0.0'

dev_dependencies:
  built_json_generator: '^0.1.5'
  built_value_generator: '^0.1.3'
  enum_class_generator: '^1.0.0'
